import = [ "~/.config/alacritty/colors.toml" ]

[shell]
program = "/bin/zsh"
args = []

[window.padding]
x = 5
y = 5

[window]
opacity = 0.8

[font]
size = 13

[font.normal]
family = "Ubuntu Mono Nerd Font"
