[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#a7987a"
red = "#f66757"
green = "#6b8f71"
yellow = "#4C3F47"
blue = "#54546e"
magenta = "#D4A140"
cyan = "#d4a140"
white = "#efdaaf"

[colors.normal]
black = "#363646"
red = "#f66757"
green = "#6b8f71"
yellow = "#7e9cd8"
blue = "#957fb8"
magenta = "#D4A140"
cyan = "#d4a140"
white = "#efdaaf"

[colors.primary]
background = "#0E0E18"
foreground = "#ffffff"